import cm_dashboards.esg.db_helper as db_helper
import cm_dashboards.esg.helpers as helpers


def get_data(wvr_path, type="report_date", report_date=None):
    """
    Get table data from df
    :param wvr_path: path to wvr file
    :param journal_name: journal name to retrive table name from (AC)
    :return: tuple (data, columns, conditional_style) for dash_table.DataTable
    """
    # Initialize DB instance
    result = list()
    match type:
        case "report_date":
            options_dict = helpers.get_date_dropdown_options()
            options = list(options_dict.keys())
            result = helpers.prepare_dropdown_options(options, name="Report date")

        case "senarios":
            # Initialize DB instance
            data = db_helper.Senarios()

            # Get data from wvr (data, columns, conditional_style)
            model_name = helpers.get_date_dropdown_options(report_date=report_date)
            date_df = helpers.get_df(data, wvr_path, model_name)
            options = date_df.values.tolist()
            result = helpers.prepare_dropdown_options(options, name="Senario")

        case "groups":
            # Initialize DB instance
            data = db_helper.Groups()

            # Get data from wvr (data, columns, conditional_style)
            model_name = helpers.get_date_dropdown_options(report_date=report_date)
            date_df = helpers.get_df(data, wvr_path, model_name)
            options = date_df.values.tolist()
            result = helpers.prepare_dropdown_options(options, name="Group")

        case "max_date":
            options_dict = helpers.get_date_dropdown_options(
                report_date=report_date, select_after=True
            )
            options = list(options_dict.keys())
            result = helpers.prepare_dropdown_options(
                options, name="Graph max date", default="AutoCalculate"
            )

        case "variables":
            # Define default variables
            options = [
                "Accounting_Model_IFRS_17",
                "Accumulated_CF_Recognised_In_OCI",
                "Accumulated_CF_Recognised_In_OCI_Opening",
                "Amortized_DAC",
                "Cash_Balance",
                "Cash_Balance_Opening",
                "Cash_Balance_Opening_Asset",
                "Cash_Balance_Reins",
                "Cash_Balance_Reins_Opening",
                "Cash_Balance_Reins_Opening_Asset",
                "Cash_This_Year",
                "Cash_This_Year_Asset",
                "Cash_This_Year_Reins",
                "Cash_This_Year_Reins_Asset",
                "CF_Benefit_Proj_Last",
                "CF_Benefit_Proj_Last_B",
                "CF_Benefit_Reinsurance_Proj_Last",
                "CF_Benefit_Reinsurance_Proj_Last_B",
                "CF_Benefit_Reinsurance_Total",
                "CF_Benefit_Total",
                "CF_Expense_Directly_Attributable",
                "CF_Expense_Directly_Attributable_CSM",
                "CF_Expense_Directly_Attributable_DiscCF",
                "CF_Expense_Directly_Attributable_LossComp",
                "CF_Expense_Directly_Attributable_Proj_Last",
                "CF_Expense_Directly_Attributable_Proj_Last_B",
                "CF_Expense_Non_Directly_Attributable",
                "CF_Expense_Non_Directly_Attributable_Proj_Last",
                "CF_Expense_Non_Directly_Attributable_Proj_Last_B",
                "CF_Expense_Non_Directly_Attributable_Reins",
                "CF_Premium_Proj_Last",
                "CF_Premium_Proj_Last_B",
                "CF_Premium_Reinsurance_Proj_Last",
                "CF_Premium_Reinsurance_Proj_Last_B",
                "CF_Premium_Reinsurance_Total",
                "CF_Premium_Total",
                "CF_Premium_Total_CSM",
                "CF_Premium_Total_DiscCF",
                "CF_Premium_Total_LossComp",
                "CF_recognised_in_OCI",
                "CF_recognised_in_OCI_Part_A",
                "CF_recognised_in_OCI_Part_B",
                "Change_Current_Service_Claims",
                "Change_Current_Service_Claims_DiscCF",
                "Change_Current_Service_Claims_LossComp",
                "Change_Current_Service_Claims_Reins",
                "Change_Current_Service_Claims_Reins_DiscCF",
                "Change_Current_Service_RA_Release",
                "Change_Current_Service_RA_Release_DiscCF",
                "Change_Current_Service_RA_Release_LossComp",
                "Change_Current_Service_RA_Release_RA",
                "Change_Current_Service_RA_Release_Reins",
                "Change_Current_Service_RA_Release_Reins_DiscCF",
                "Change_Current_Service_RA_Release_Reins_RA",
                "Change_Future_Services",
                "Change_Future_Services_CSM",
                "Change_Future_Services_CSM_A",
                "Change_Future_Services_CSM_B",
                "Change_Future_Services_DiscCF",
                "Change_Future_Services_DiscCF_A",
                "Change_Future_Services_DiscCF_B",
                "Change_Future_Services_FCF",
                "Change_Future_Services_FCF_B",
                "Change_Future_Services_FCF_IFE",
                "Change_Future_Services_FCF_IFE_A",
                "Change_Future_Services_FCF_IFE_B",
                "Change_Future_Services_LossComp",
                "Change_Future_Services_LossComp_A",
                "Change_Future_Services_LossComp_B",
                "Change_Future_Services_NewBus",
                "Change_Future_Services_NewBus_CSM",
                "Change_Future_Services_NewBus_DiscCF",
                "Change_Future_Services_NewBus_LossComp",
                "Change_Future_Services_NewBus_RA",
                "Change_Future_Services_NewBus_Reins",
                "Change_Future_Services_NewBus_Reins_CSM",
                "Change_Future_Services_NewBus_Reins_DiscCF",
                "Change_Future_Services_NewBus_Reins_RA",
                "Change_Future_Services_RA",
                "Change_Future_Services_RA_A",
                "Change_Future_Services_RA_B",
                "Change_Future_Services_Reins",
                "Change_Future_Services_Reins_CSM",
                "Change_Future_Services_Reins_CSM_A",
                "Change_Future_Services_Reins_CSM_B",
                "Change_Future_Services_Reins_DiscCF",
                "Change_Future_Services_Reins_DiscCF_A",
                "Change_Future_Services_Reins_DiscCF_B",
                "Change_Future_Services_Reins_FCF",
                "Change_Future_Services_Reins_RA",
                "Change_Future_Services_Reins_RA_A",
                "Change_Future_Services_Reins_RA_B",
                "Change_In_Fair_Value",
                "Change_In_Fair_Value_CSM",
                "Change_In_Fair_Value_DiscCF",
                "Change_In_Fair_Value_LossComp",
                "Contractual_Service_Margin",
                "Contractual_Service_Margin_Opening",
                "Contractual_Service_Margin_Reins",
                "Contractual_Service_Margin_Reins_Opening",
                "DAC_Initial_Adj",
                "Disc_CF",
                "Disc_CF_Adj_Proj",
                "Disc_CF_Curr_DR_Proj",
                "Disc_CF_Opening",
                "Disc_CF_Orig_DR_Proj",
                "Disc_CF_Reins_Opening",
                "Disc_CF_Reinsurance",
                "Disc_CF_Reinsurance_Curr_DR_Proj",
                "Disc_CF_Reinsurance_Orig_DR_Proj",
                "Disc_Rate_CSM",
                "Disc_Rate_Curr",
                "Disc_Rate_Orig",
                "Disc_Time_Value_Curr_DR",
                "Disc_Time_Value_Orig_DR",
                "Disc_Time_Value_Reins_Curr_DR",
                "Disc_Time_Value_Reins_Orig_DR",
                "Experience_Adj_Current_Service",
                "Experience_Adj_Current_Service_B",
                "Experience_Adj_Current_Service_Ben",
                "Experience_Adj_Current_Service_Ben_A",
                "Experience_Adj_Current_Service_Ben_B",
                "Experience_Adj_Current_Service_Ben_Reins",
                "Experience_Adj_Current_Service_Ben_Reins_A",
                "Experience_Adj_Current_Service_Ben_Reins_B",
                "Experience_Adj_Current_Service_Exp",
                "Experience_Adj_Current_Service_Exp_A",
                "Experience_Adj_Current_Service_Exp_B",
                "Experience_Adj_Current_Service_NDA_Exp",
                "Experience_Adj_Current_Service_NDA_Exp_A",
                "Experience_Adj_Current_Service_NDA_Exp_B",
                "Experience_Adj_Current_Service_Prem",
                "Experience_Adj_Current_Service_Prem_A",
                "Experience_Adj_Current_Service_Prem_B",
                "Experience_Adj_Current_Service_Prem_Reins",
                "Experience_Adj_Current_Service_Prem_Reins_A",
                "Experience_Adj_Current_Service_Prem_Reins_B",
                "Experience_Adj_Current_Service_Reins",
                "Experience_Adj_Current_Service_Reins_B",
                "Experience_Adj_Future_Service",
                "Experience_Adj_Future_Service_B",
                "Experience_Adj_Future_Service_Ben",
                "Experience_Adj_Future_Service_Ben_A",
                "Experience_Adj_Future_Service_Ben_B",
                "Experience_Adj_Future_Service_Ben_Reins",
                "Experience_Adj_Future_Service_Ben_Reins_A",
                "Experience_Adj_Future_Service_Ben_Reins_B",
                "Experience_Adj_Future_Service_Exp",
                "Experience_Adj_Future_Service_Exp_A",
                "Experience_Adj_Future_Service_Exp_B",
                "Experience_Adj_Future_Service_Prem",
                "Experience_Adj_Future_Service_Prem_A",
                "Experience_Adj_Future_Service_Prem_B",
                "Experience_Adj_Future_Service_Prem_Reins",
                "Experience_Adj_Future_Service_Prem_Reins_A",
                "Experience_Adj_Future_Service_Prem_Reins_B",
                "Experience_Adj_Future_Service_Reins",
                "Experience_Adj_FX",
                "Experience_Adj_FX_Reins",
                "Experience_Adj_InvComp",
                "Experience_Adj_InvComp_B",
                "Fair_Value_PolicyHolder_Share",
                "Fair_Value_Transition",
                "Fair_Value_Transition_Reins",
                "Fulfilment_Cash_Flows",
                "Fulfilment_Cash_Flows_Proj_Last",
                "Fulfilment_Cash_Flows_Proj_Last_B",
                "Fulfilment_Cash_Flows_Reins",
                "Fulfilment_Cash_Flows_Reins_Proj_Last",
                "Fulfilment_Cash_Flows_Reins_Proj_Last_B",
                "Group_Asset_Flag",
                "Group_Asset_Reins_Flag",
                "Group_ID",
                "Inc_In_DAC",
                "Inception_Date",
                "Income_Proj_All",
                "Income_Reins_Proj_All",
                "Incurred_Claims",
                "Incurred_Claims_and_Expenses",
                "Incurred_Claims_and_Expenses_Reins",
                "Insurance_Contract_Liability_Asset",
                "Insurance_Contract_Liability_Opening",
                "Insurance_Contract_Liability_Reins",
                "Insurance_Contract_Liability_Reins_Asset",
                "Insurance_Contract_Liability_Reins_Opening",
                "Insurance_Contract_Revenue",
                "Insurance_Contract_Revenue_CSM",
                "Insurance_Contract_Revenue_DiscCF",
                "Insurance_Contract_Revenue_LossComp",
                "Insurance_Contract_Revenue_RA",
                "Insurance_Contract_Revenue_Reins",
                "Insurance_Contract_Revenue_Reins_CSM",
                "Insurance_Contract_Revenue_Reins_DiscCF",
                "Insurance_Contract_Revenue_Reins_RA",
                "Insurance_Finance_Expenses",
                "Insurance_Finance_Expenses_CSM",
                "Insurance_Finance_Expenses_DiscCF",
                "Insurance_Finance_Expenses_LossComp",
                "Insurance_Finance_Expenses_Reins",
                "Insurance_Finance_Expenses_Reins_CSM",
                "Insurance_Finance_Expenses_Reins_DiscCF",
                "Insurance_Revenue",
                "Insurance_Revenue_Reins",
                "Insurance_Service_Expenses",
                "Insurance_Service_Expenses_Reins",
                "Insurance_Service_Related_Result",
                "Insurance_Service_Related_Result_CSM",
                "Insurance_Service_Related_Result_DiscCF",
                "Insurance_Service_Related_Result_IncClaim",
                "Insurance_Service_Related_Result_LossComp",
                "Insurance_Service_Related_Result_RA",
                "Insurance_Service_Related_Result_Reins",
                "Insurance_Service_Related_Result_Reins_CSM",
                "Insurance_Service_Related_Result_Reins_DiscCF",
                "Insurance_Service_Related_Result_Reins_IncClaim",
                "Insurance_Service_Related_Result_Reins_RA",
                "Insurance_Service_Result",
                "Insurance_Service_Result_Reins",
                "Investment_Component",
                "Investment_Component_CSM",
                "Investment_Component_DiscCF",
                "Investment_Component_IncClaim",
                "Investment_Component_LossComp",
                "Investment_Component_Proj_Last",
                "Investment_Component_Proj_Last_B",
                "Investment_Component_Reins",
                "Investment_Component_Reins_DiscCF",
                "Investment_Component_Reins_IncClaim",
                "Investment_Income",
                "Liability_Incurred_Claims",
                "Liability_Incurred_Claims_Opening",
                "Liability_Incurred_Claims_Reins",
                "Liability_Incurred_Claims_Reins_Opening",
                "Loss_Component",
                "Loss_Component_Opening",
                "Loss_Component_Systematic_PC",
                "Loss_On_Onerous_Group",
                "Loss_On_Onerous_Group_CSM",
                "Loss_On_Onerous_Group_DiscCF",
                "Loss_On_Onerous_Group_LossComp",
                "Loss_On_Onerous_Group_Reins_CSM",
                "Loss_Recovery_Reins",
                "Loss_Recovery_Reins_Opening",
                "Model_End_Date",
                "Non_Insurance_Related_Result",
                "Non_Insurance_Related_Result_CSM",
                "Non_Insurance_Related_Result_DiscCF",
                "Non_Insurance_Related_Result_IncClaim",
                "Non_Insurance_Related_Result_LossComp",
                "Non_Insurance_Related_Result_RA",
                "Non_Insurance_Related_Result_Reins",
                "Non_Insurance_Related_Result_Reins_CSM",
                "Non_Insurance_Related_Result_Reins_DiscCF",
                "Non_Insurance_Related_Result_Reins_IncClaim",
                "Non_Insurance_Related_Result_Reins_RA",
                "Other_Comprehensive_Income",
                "Outgo_Proj_All",
                "Outgo_Reins_Proj_All",
                "Outgo_Total",
                "Outgo_Total_Paid",
                "Outgo_Total_Paid_Claims",
                "Outgo_Total_Proj_Last",
                "Outgo_Total_Proj_Last_B",
                "Outgo_Total_Reins",
                "Outgo_Total_Reins_Paid",
                "Outgo_Total_Reins_Proj_Last",
                "Outgo_Total_Reins_Proj_Last_B",
                "Pattern_Of_Service_PC",
                "Profit_Loss",
                "Profit_Loss_Reins",
                "PV_Income_Orig_DR_Proj",
                "PV_Income_Reins_Orig_DR_Proj",
                "PV_Outgo_Orig_DR_Proj",
                "PV_Outgo_Reins_Orig_DR_Proj",
                "Risk_Adjustment",
                "Risk_Adjustment_Opening",
                "Risk_Adjustment_Proj_Last",
                "Risk_Adjustment_Proj_Last_B",
                "Risk_Adjustment_Reins",
                "Risk_Adjustment_Reins_Opening",
                "Risk_Adjustment_Reins_Proj_Last",
                "Risk_Adjustment_Reins_Proj_Last_B",
                "Scenario_Number_RW",
            ]
            result = helpers.prepare_dropdown_options(
                options,
                name="Scatter Plot variable",
                default="Insurance_Contract_Liability",
            )

        case _:
            pass

    return result
